Repository AY2122S1-CS2103-F09-1/tp, pull requests merged in 2021-11, with the labels that each got.

#150 Add testing files for all classes within Task package
  src/main/java/seedu/address/model/task/UniqueTaskList.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/task/TaskDeadlineTest.java
  src/test/java/seedu/address/model/task/TaskIdTest.java
  src/test/java/seedu/address/model/task/TaskNameTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/model/task/UniqueTaskListTest.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: testing

#212 Branch ruofan update uml
  docs/DeveloperGuide.md
  docs/Gemfile.lock
  docs/_layouts/default.html
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteModuleSequenceDiagram1.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/moduleSequenceDiagram/AddModuleSequenceDiagram1.puml
  docs/diagrams/moduleSequenceDiagram/AddModuleSequenceDiagram2.puml
  docs/diagrams/moduleSequenceDiagram/DeleteModuleSequenceDiagram1.puml
  docs/diagrams/moduleSequenceDiagram/DeleteModuleSequenceDiagram2.puml
  docs/diagrams/moduleSequenceDiagram/EditModuleSequenceDiagram1.puml
  docs/diagrams/moduleSequenceDiagram/EditModuleSequenceDiagram2.puml
  docs/diagrams/studentSequenceDiagram/AddStudentSequenceDiagram1.puml
  docs/diagrams/studentSequenceDiagram/AddStudentSequenceDiagram2.puml
  docs/diagrams/studentSequenceDiagram/DeleteStudentSequenceDiagram.puml
  docs/diagrams/studentSequenceDiagram/DeleteStudentSequenceDiagram1.puml
  docs/diagrams/studentSequenceDiagram/DeleteStudentSequenceDiagram2.puml
  docs/diagrams/studentSequenceDiagram/EditStudentSequenceDiagram1.puml
  docs/diagrams/studentSequenceDiagram/EditStudentSequenceDiagram2.puml
  docs/diagrams/studentSequenceDiagram/FindStudentSequenceDiagram1.puml
  docs/diagrams/studentSequenceDiagram/FindStudentSequenceDiagram2.puml
  docs/diagrams/taskSequenceDiagram/AddTaskSequenceDiagram1.puml
  docs/diagrams/taskSequenceDiagram/AddTaskSequenceDiagram2.puml
  docs/diagrams/taskSequenceDiagram/DeleteTaskSequenceDiagram1.puml
  docs/diagrams/taskSequenceDiagram/DeleteTaskSequenceDiagram2.puml
  docs/diagrams/taskSequenceDiagram/EditTaskSequenceDiagram1.puml
  docs/diagrams/taskSequenceDiagram/EditTaskSequenceDiagram2.puml
  docs/images/AddModuleSequenceDiagram1.png
  docs/images/AddModuleSequenceDiagram2.png
  docs/images/AddStudentSequenceDiagram1.png
  docs/images/AddTaskSequenceDiagram1.png
  docs/images/AddTaskSequenceDiagram2.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteModuleSequenceDiagram1.png
  docs/images/DeleteStudentSequenceDiagram1.png
  docs/images/DeleteStudentSequenceDiagram2.png
  docs/images/DeleteTaskSequenceDiagram1.png
  docs/images/DeleteTaskSequenceDiagram2.png
  docs/images/EditModuleSequenceDiagram1.png
  docs/images/EditModuleSequenceDiagram2.png
  docs/images/EditStudentSequenceDiagram1.png
  docs/images/EditTaskSequenceDiagram1.png
  docs/images/EditTaskSequenceDiagram2.png
  docs/images/FindStudentSequenceDiagram1.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: documentation

#214 Update User Guide to fix Must-Fix issues identified in the PE-D
  README.md
  docs/UserGuide.md
Labels: documentation

#225 Update DG
  docs/DeveloperGuide.md
Labels: documentation

#224 Branch mengzhe add testing for task done undone
  src/test/java/seedu/address/logic/commands/MarkTaskDoneCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkTaskUndoneCommandTest.java
  src/test/java/seedu/address/logic/parser/MarkTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MarkTaskDoneCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MarkTaskUndoneCommandParserTest.java
Labels: testing

#227 Branch mengzhe check duplicate tele handle email
  src/main/java/seedu/address/logic/commands/AddStudentCommand.java
  src/main/java/seedu/address/logic/commands/EditStudentCommand.java
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
  src/test/java/seedu/address/logic/commands/EditStudentCommandTest.java
Labels: Must Fix

#226 Update Ruofan's PPP
  docs/AboutUs.md
  docs/team/ruofan.md
  docs/team/ruofan1023.md
Labels: documentation

#231 Update Joseph's PPP
  README.md
  docs/AboutUs.md
  docs/UserGuide.md
  docs/team/wanggljoseph.md
  docs/team/wangguanlinjoseph.md
Labels: documentation

#229 Update Felissa's PPP
  docs/AboutUs.md
  docs/team/felissa.md
  docs/team/felissaf.md
Labels: documentation

#219 Branch mengzhe add model module testing
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/module/ModuleNameEqualsKeywordPredicateTest.java
  src/test/java/seedu/address/model/module/ModuleNameTest.java
  src/test/java/seedu/address/model/module/ModuleTest.java
  src/test/java/seedu/address/model/module/UniqueModuleListTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/TypicalModules.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: testing

#237 Branch joseph update user guide
  build.gradle
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/UserGuide.md
  docs/_sass/minima/_base.scss
  docs/images/Ui.png
  docs/team/charliemoweng.md
  docs/team/felissaf.md
  docs/team/ruofan1023.md
  docs/team/tanjoewel.md
  docs/team/wanggljoseph.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyTeachingAssistantBuddy.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/storage/JsonSerializableAssistantBuddy.java
  src/main/java/seedu/address/storage/JsonTeachingAssistantBuddyStorage.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/commons/core/index/IndexTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteStudentCommandTest.java
  src/test/java/seedu/address/logic/parser/TeachingAssistantBuddyParserTest.java
  src/test/java/seedu/address/model/module/student/StudentIdEqualsKeywordPredicateTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/EditStudentDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: documentation

#242 Add Effort section to DG
  docs/DeveloperGuide.md
Labels: documentation
